name: Deploy to AWS Lambda
on: [push, pull_request]
jobs:
  deploy_source:
    name: Build and deploy Lambda

    strategy:
      matrix:
        python-version: [3.7]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy code to Lambda
        uses: mariamrf/py-lambda-action@v1.0.1
        with:
          lambda_layer_arn: ${{ secrets.AWS_LAMBDA_LAYER }}
          lambda_function_name: ${{ secrets.AWS_FUNCTION_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'